# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_url', models.URLField()),
                ('app_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('currency', models.DecimalField(decimal_places=2, max_digits=8)),
                ('screenshots', models.CharField(max_length=200)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Language')),
            ],
        ),
    ]
