# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='screenshots',
            new_name='advisories',
        ),
        migrations.RemoveField(
            model_name='music',
            name='date_created',
        ),
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='currency',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='languages',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
